name: "livox_driver2"
version: "0.1.0"
description: "Driver for Livox LiDARs"
maintainers:
  - name: "fins"
    email: "fins@sjtu.edu.cn"
depends:
  PCL: "system"

  std_msgs: "system"
  sensor_msgs: "system"
  pcl_conversions: "system"
  livox_msg: "1.0.1"
  LivoxSDK: "1.3.1"

recipes:
  livox_msg:
    git: "https://github.com/Han-Yu-Meng/livox_msg.git"
    build_system: "cmake"
    versions:
      "1.0.1":
        tag: "v1.0.1"

  LivoxSDK:
    git: "https://github.com/Han-Yu-Meng/Livox-SDK2"
    build_system: "cmake"
    versions:
      "1.3.1":
        tag: "v1.3.1-patched"
        
licenses:
  - "MIT"